apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidartdesai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sidartdesai
  template:
    metadata:
      labels:
        app: sidartdesai
    spec:
      containers:
        - name: springboot
          image: docker-image:tag

          resources:
            requests:
              memory: "128Mi"
              cpu: "512m"
            limits:
              memory: "128Mi"
              cpu: "512m"

          ports:
            - containerPort: 8080

          readinessProbe:
            httpGet:
              path: /test
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /test
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10

          startupProbe:
            httpGet:
              path: /test
              port: 8080
            failureThreshold: 30
            periodSeconds: 10

          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: jhooq-springboot
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: jhooq-springboot
